---
# tasks file for ./roles/Esm
- name: Copy Tomcat tar file to EsmProj folder
  copy:
    src: /home/kvnblue/Downloads/apache-tomcat-8.5.32.tar.gz
    dest: /home/kvnblue/EsmAns/EsmProj
- name: Extract Tomcat tar file
  unarchive:
    src: /home/kvnblue/EsmAns/EsmProj/apache-tomcat-8.5.32.tar.gz
    dest: /home/kvnblue/EsmAns/EsmProj
- name: change startup.sh file permissions
  file:
    path: /home/kvnblue/EsmAns/EsmProj/apache-tomcat-8.5.32/bin/startup.sh
    mode: 0777
- name: change catalina.sh file permissions
  file:
    path: /home/kvnblue/EsmAns/EsmProj/apache-tomcat-8.5.32/bin/catalina.sh
    mode: 0777
- name: Copy Esm dist folder to tomcat webapps root folder
  copy:
    src: /home/kvnblue/Downloads/EsmSite/dist
    dest: /home/kvnblue/EsmAns/EsmProj/apache-tomcat-8.5.32/webapps/ROOT
- name: start tomcat service
  shell: /home/kvnblue/EsmAns/EsmProj/apache-tomcat-8.5.32/bin/startup.sh
